
#include <termios.h>


#define FALSE 0
#define TRUE 1

#define TRANSMITTER 0 
#define RECEIVER 1

#define FLAG 0x7E
#define ADDRESS_FIELD 0x03
#define CONTROL_BYTE_0   0x00
#define CONTROL_BYTE_1   0x40
#define CONTROL_BYTE_SET 0x03
#define CONTROL_BYTE_UA 0x07
#define CONTROL_BYTE_DISC 0x0B
#define CONTROL_BYTE_REJ0 0x01
#define CONTROL_BYTE_REJ1 0x81
#define CONTROL_BYTE_RR0 0x05
#define CONTROL_BYTE_RR1 0x85


#define CONTROL_BYTE_START 0x02
#define CONTROL_BYTE_END 0x03
#define CONTROL_BYTE_DATA 0x01


#define FILE_SIZE_BYTE 0x00
#define FILE_NAME_BYTE 0x01
#define BYTE_MASK 0xFF

#define ESC_BYTE 0x7D
#define STUFFING_BYTE 0x20


#define MAX_TRIES 3

enum state{START, FLG_RCV, A_RCV, C_RCV, BCC_OK, STOP, DATA_RCV};
